In [30]:
import cv2
import numpy as np

### understand image

In [45]:
image = cv2.imread("random.png")
trial = image.copy()
trial.shape

#(3024, 4032, 3) --> cols, rows, 3 channels ?
# 3024 rows 4032 col

(3024, 4032, 3)

In [48]:
cv2.imshow("red", trial[:, :, 0]) 
# try to plot all 3 channels
cv2.waitKey(0)
cv2.destroyAllWindows()

: 

In [4]:
trial[0][1] #output is an array of length 3 to mean BGR. 

array([ 80, 105, 131], dtype=uint8)

In [5]:
channels = trial[2]
trial[2].shape #there are 3 channels represented in this array


(4032, 3)

In [11]:
channels[2] #for 4032 rows, there are 3 values, one for each channel

array([ 81, 108, 135], dtype=uint8)

In [13]:
B = 0
G = 1
R = 2

row = 1 #can change this val from 0 to 4032

In [14]:
channels[row][B] #b value for row 4032. 

82

### goal is to plot one channel (done)

In [15]:
green_channel = trial[:, :, 0] #should be the entire image but just in blue. it isn't, its greyscale. since we selected a value for the channel, this is just a 2d array between 0 to 255 now. 
#to show the colors, must add the third dimension back but set green and red to zeroes. 
red_channel = trial[:, :, 1]
red_channel.shape

(3024, 4032)

In [16]:
green_img = np.zeros(trial.shape)
red_img = np.zeros(trial.shape)

green_img[:, :, 1] = green_channel
red_img[:, :, 1] = red_channel

In [13]:
cv2.imshow("R", red_img) 
# try to plot all 3 channels
cv2.waitKey(0)
cv2.destroyAllWindows()

: 

In [4]:
cv2.imshow("trial", trial) 
# try to plot all 3 channels
cv2.waitKey(0)
cv2.destroyAllWindows()

width, height, channels
pick a channel - channel 1, and select a value for width and height --> scalar
all width and all height for one channel - a 2d array with values being the intensity of the channel

In [ ]:
G, B, R

array practice

In [82]:
arr = [[[4, 5, 6],[11, 6, 4],[5, 2, 4]], [4, 5, 6],[7,8,9]]
arr[:, :]


TypeError: list indices must be integers or slices, not tuple

what is a 3d array?

In [92]:
oned = [1,2,3]
# oned[0]
oned[:]

[1, 2, 3]

In [93]:
twod = [[1,2,3], [4,5,6], [7,8,9]]
# twod[0]
twod[:, :]

TypeError: list indices must be integers or slices, not tuple

In [97]:
threed = [[[1,2,3],[1,2,3],[4,5,6]], [[1,2,3],[1,2,3],[4,5,6]], [[1,2,3],[1,2,3],[4,5,6]],]
# threed[0][1][2]
threed = np.array(threed)
selected_columns = threed[:, :]
print(selected_columns)

[[[1 2 3]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [1 2 3]
  [4 5 6]]]
